// Hand-written transport. Types.swift next to it is generated by gotypegen
// (go/api: make types) — never edit that one.

@preconcurrency import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

public enum InferenceError: Error, LocalizedError, Sendable {
    case http(status: Int, body: String)
    case noAssistantMessage
    case transport(String)

    public var errorDescription: String? {
        switch self {
        case .http(let status, let body): return "HTTP \(status): \(body)"
        case .noAssistantMessage: return "No assistant message in response (message was queued?)"
        case .transport(let s): return s
        }
    }
}

public struct InferenceClient: Sendable {
    public var baseURL: URL
    public var apiKey: String

    public init(baseURL: URL = URL(string: "https://api.inference.sh")!, apiKey: String) {
        self.baseURL = baseURL
        self.apiKey = apiKey
    }

    // MARK: - Agents

    /// POST /agents/run without streaming. Returns immediately; the assistant
    /// message is usually still `pending`.
    public func runAgent(_ body: ApiAgentRunRequest) async throws -> CreateAgentMessageResponse {
        var body = body
        body.stream = false
        let (data, status) = try await send(request("agents/run", accept: "application/json", body: body))
        guard (200..<300).contains(status) else {
            throw InferenceError.http(status: status, body: String(decoding: data, as: UTF8.self))
        }
        return try Self.decoder.decode(CreateAgentMessageResponse.self, from: data)
    }

    /// POST /agents/run with `stream: true`. Yields assistant message snapshots
    /// (full DTO each time, not deltas) until the message reaches a terminal
    /// status. Uses NDJSON: one object per line, `{"type":"heartbeat"}` every
    /// 10s, aux events wrapped as `{"event":..,"data":..}`.
    public func runAgentStream(_ body: ApiAgentRunRequest) -> AsyncThrowingStream<ChatMessageDTO, Error> {
        AsyncThrowingStream { continuation in
            let task = Task {
                do {
                    var body = body
                    body.stream = true
                    let req = try request("agents/run", accept: "application/x-ndjson", body: body)
                    let lines = HTTPLineStream(request: req)
                    let (status, contentType) = try await lines.start()
                    guard (200..<300).contains(status) else {
                        var text = ""
                        for try await line in lines.lines { text += line }
                        throw InferenceError.http(status: status, body: text)
                    }

                    if !contentType.contains("ndjson") {
                        // Plain JSON answer: message queued on a busy chat.
                        var text = ""
                        for try await line in lines.lines { text += line }
                        let resp = try Self.decoder.decode(CreateAgentMessageResponse.self, from: Data(text.utf8))
                        guard let msg = resp.assistantMessage else { throw InferenceError.noAssistantMessage }
                        continuation.yield(msg)
                        continuation.finish()
                        return
                    }

                    for try await line in lines.lines {
                        if Task.isCancelled { break }
                        guard let msg = Self.parseStreamLine(line), msg.role == .assistant else { continue }
                        continuation.yield(msg)
                        if msg.status.isTerminal { break }
                    }
                    continuation.finish()
                } catch {
                    continuation.finish(throwing: error)
                }
            }
            continuation.onTermination = { _ in task.cancel() }
        }
    }

    /// One NDJSON line → ChatMessageDTO, or nil for heartbeats, aux events and partial-field wrappers.
    public static func parseStreamLine(_ line: String) -> ChatMessageDTO? {
        let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.hasPrefix("{") else { return nil }
        let data = Data(trimmed.utf8)
        if let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
           obj["type"] as? String == "heartbeat" || obj["event"] != nil || obj["fields"] != nil {
            return nil
        }
        return try? decoder.decode(ChatMessageDTO.self, from: data)
    }

    // MARK: - Plumbing

    public static let decoder = JSONDecoder()
    public static let encoder = JSONEncoder()

    func request<B: Encodable>(_ path: String, accept: String, body: B) throws -> URLRequest {
        var req = URLRequest(url: baseURL.appendingPathComponent(path))
        req.httpMethod = "POST"
        req.setValue("Bearer \(apiKey)", forHTTPHeaderField: "Authorization")
        req.setValue("2", forHTTPHeaderField: "X-API-Version")
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.setValue(accept, forHTTPHeaderField: "Accept")
        req.timeoutInterval = 300
        req.httpBody = try Self.encoder.encode(body)
        return req
    }

    private func send(_ req: URLRequest) async throws -> (Data, Int) {
        try await withCheckedThrowingContinuation { c in
            URLSession.shared.dataTask(with: req) { data, resp, err in
                if let err { c.resume(throwing: InferenceError.transport(err.localizedDescription)); return }
                c.resume(returning: (data ?? Data(), (resp as? HTTPURLResponse)?.statusCode ?? 0))
            }.resume()
        }
    }
}

// MARK: - Convenience on generated types

public extension ChatMessageStatus {
    /// Mirrors ChatMessageStatus.IsTerminal() in Go.
    var isTerminal: Bool { self == .ready || self == .failed || self == .cancelled }
}

public extension ChatMessageDTO {
    /// Concatenated text blocks.
    var text: String {
        (content ?? []).filter { $0.type == .text }.compactMap(\.text).joined()
    }
    var errorText: String? {
        (content ?? []).compactMap(\.error).first
    }
}

// MARK: - Line-oriented HTTP body stream (delegate based: works on Linux too,
// unlike URLSession.bytes(for:)).

final class HTTPLineStream: NSObject, URLSessionDataDelegate, @unchecked Sendable {
    private let request: URLRequest
    private var session: URLSession!
    private var buffer = Data()
    private var headerContinuation: CheckedContinuation<(Int, String), Error>?
    private var lineContinuation: AsyncThrowingStream<String, Error>.Continuation!
    let lines: AsyncThrowingStream<String, Error>

    init(request: URLRequest) {
        self.request = request
        var cont: AsyncThrowingStream<String, Error>.Continuation!
        lines = AsyncThrowingStream { cont = $0 }
        super.init()
        lineContinuation = cont
        session = URLSession(configuration: .default, delegate: self, delegateQueue: nil)
    }

    /// Starts the request and resolves once headers arrive.
    func start() async throws -> (Int, String) {
        try await withCheckedThrowingContinuation { c in
            headerContinuation = c
            session.dataTask(with: request).resume()
        }
    }

    func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didReceive response: URLResponse,
                    completionHandler: @escaping (URLSession.ResponseDisposition) -> Void) {
        let http = response as? HTTPURLResponse
        let ct = (http?.value(forHTTPHeaderField: "Content-Type") ?? "").lowercased()
        headerContinuation?.resume(returning: (http?.statusCode ?? 0, ct))
        headerContinuation = nil
        completionHandler(.allow)
    }

    func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didReceive data: Data) {
        buffer.append(data)
        while let nl = buffer.firstIndex(of: 0x0A) {
            let line = String(decoding: buffer[buffer.startIndex..<nl], as: UTF8.self)
            buffer.removeSubrange(buffer.startIndex...nl)
            lineContinuation.yield(line)
        }
    }

    func urlSession(_ session: URLSession, task: URLSessionTask, didCompleteWithError error: Error?) {
        if let error {
            headerContinuation?.resume(throwing: InferenceError.transport(error.localizedDescription))
            headerContinuation = nil
            lineContinuation.finish(throwing: InferenceError.transport(error.localizedDescription))
        } else {
            if !buffer.isEmpty { lineContinuation.yield(String(decoding: buffer, as: UTF8.self)) }
            lineContinuation.finish()
        }
        session.finishTasksAndInvalidate()
    }
}
